name: flutter_application_1
description: A Flutter app to list cryptocurrencies using CoinMarketCap API.
version: 1.0.0
environment:
  sdk: '>=2.18.0 <3.0.0'
dependencies:
  flutter:
    sdk: flutter
  http: ^0.13.5
  provider: ^6.0.5
  intl: ^0.17.0
  pull_to_refresh: ^2.0.0
dev_dependencies:
  flutter_test:
    sdk: flutter
flutter:
  uses-material-design: true